// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// Summarizer is a mock implementation of events.summarizer.
//
//	func TestSomethingThatUsessummarizer(t *testing.T) {
//
//		// make and configure a mocked events.summarizer
//		mockedsummarizer := &Summarizer{
//			SummaryFunc: func(link string) (string, error) {
//				panic("mock out the Summary method")
//			},
//		}
//
//		// use mockedsummarizer in code that requires events.summarizer
//		// and then make assertions.
//
//	}
type Summarizer struct {
	// SummaryFunc mocks the Summary method.
	SummaryFunc func(link string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Summary holds details about calls to the Summary method.
		Summary []struct {
			// Link is the link argument value.
			Link string
		}
	}
	lockSummary sync.RWMutex
}

// Summary calls SummaryFunc.
func (mock *Summarizer) Summary(link string) (string, error) {
	if mock.SummaryFunc == nil {
		panic("Summarizer.SummaryFunc: method is nil but summarizer.Summary was just called")
	}
	callInfo := struct {
		Link string
	}{
		Link: link,
	}
	mock.lockSummary.Lock()
	mock.calls.Summary = append(mock.calls.Summary, callInfo)
	mock.lockSummary.Unlock()
	return mock.SummaryFunc(link)
}

// SummaryCalls gets all the calls that were made to Summary.
// Check the length with:
//
//	len(mockedsummarizer.SummaryCalls())
func (mock *Summarizer) SummaryCalls() []struct {
	Link string
} {
	var calls []struct {
		Link string
	}
	mock.lockSummary.RLock()
	calls = mock.calls.Summary
	mock.lockSummary.RUnlock()
	return calls
}
